apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-poc.fullname" . }}-ring-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-poc.labels" . | nindent 4 }}
    app.kubernetes.io/component: ring-store
spec:
  replicas: {{ .Values.store.replicas }}
  selector:
    matchLabels:
      {{- include "sample-poc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ring-store
  template:
    metadata:
      labels:
        {{- include "sample-poc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ring-store
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ring-store
          image: {{ include "sample-poc.image" (index .Values.images "ring-store") | quote }}
          imagePullPolicy: {{ (index .Values.images "ring-store").pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.store.port }}
          env:
            - name: BUFFER_SIZE
              value: {{ .Values.collector.bufferSize | quote }}
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.store.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
