apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-poc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "sample-poc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-poc.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: {{ include "sample-poc.image" (index .Values.images "app") | quote }}
          imagePullPolicy: {{ (index .Values.images "app").pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
