{{- if .Values.karmada.enabled }}
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ include "sample-poc.fullname" . }}-ring-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-poc.labels" . | nindent 4 }}
spec:
  conflictResolution: Abort
  preemption: Never
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "sample-poc.fullname" . }}-ring-store
      namespace: {{ .Release.Namespace }}
    - apiVersion: v1
      kind: Service
      name: {{ include "sample-poc.fullname" . }}-ring-store
      namespace: {{ .Release.Namespace }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- toYaml .Values.karmada.placement.store.clusterNames | nindent 8 }}
{{- end }}
