{{- if .Values.karmada.enabled }}
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: {{ include "sample-poc.fullname" . }}-metrics-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-poc.labels" . | nindent 4 }}
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "sample-poc.fullname" . }}-metrics-collector
      namespace: {{ .Release.Namespace }}
  overrideRules:
    - targetCluster:
        clusterNames:
          - b
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/-
            operator: add
            value:
              name: SITE_NAME
              value: "b"
    - targetCluster:
        clusterNames:
          - c
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/-
            operator: add
            value:
              name: SITE_NAME
              value: "c"
{{- end }}
